"""initial_schema

Revision ID: 227616866937
Revises: 
Create Date: 2025-10-12 21:27:29.852757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227616866937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cuota_base', sa.Float(), nullable=False),
    sa.Column('tiene_cuota_fija', sa.Boolean(), nullable=False),
    sa.Column('caracteristicas', sa.Text(), nullable=True),
    sa.Column('modulo_tipo', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('eventos_acceso',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.String(length=255), nullable=False),
    sa.Column('fecha_fin', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('requiere_validacion_especial', sa.Boolean(), nullable=True),
    sa.Column('solo_categoria_especifica', sa.String(length=100), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_acceso_id'), 'eventos_acceso', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.Enum('SUPER_ADMIN', 'ADMINISTRADOR', 'OPERADOR', 'PORTERO', 'CONSULTA', name='rolusuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('miembros',
    sa.Column('numero_miembro', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento', sa.Enum('DNI', 'PASAPORTE', 'CUIL', 'CUIT', 'OTRO', name='tipodocumento'), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'MOROSO', 'SUSPENDIDO', 'BAJA', name='estadomiembro'), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('qr_hash', sa.String(length=64), nullable=False),
    sa.Column('qr_generated_at', sa.String(length=255), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('saldo_cuenta', sa.Float(), nullable=False),
    sa.Column('ultima_cuota_pagada', sa.Date(), nullable=True),
    sa.Column('proximo_vencimiento', sa.Date(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('modulo_tipo', sa.String(length=50), nullable=False),
    sa.Column('metadatos', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_hash')
    )
    op.create_index(op.f('ix_miembros_email'), 'miembros', ['email'], unique=False)
    op.create_index(op.f('ix_miembros_estado'), 'miembros', ['estado'], unique=False)
    op.create_index(op.f('ix_miembros_id'), 'miembros', ['id'], unique=False)
    op.create_index(op.f('ix_miembros_numero_documento'), 'miembros', ['numero_documento'], unique=True)
    op.create_index(op.f('ix_miembros_numero_miembro'), 'miembros', ['numero_miembro'], unique=True)
    op.create_index(op.f('ix_miembros_qr_code'), 'miembros', ['qr_code'], unique=True)
    op.create_table('accesos',
    sa.Column('miembro_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.String(length=255), nullable=False),
    sa.Column('tipo_acceso', sa.Enum('QR', 'MANUAL', 'CREDENCIAL', 'RECONOCIMIENTO', name='tipoacceso'), nullable=False),
    sa.Column('resultado', sa.Enum('PERMITIDO', 'RECHAZADO', 'ADVERTENCIA', name='resultadoacceso'), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('dispositivo_id', sa.String(length=100), nullable=True),
    sa.Column('qr_code_escaneado', sa.String(length=255), nullable=True),
    sa.Column('qr_validacion_exitosa', sa.Boolean(), nullable=True),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.String(length=50), nullable=True),
    sa.Column('longitud', sa.String(length=50), nullable=True),
    sa.Column('estado_miembro_snapshot', sa.String(length=50), nullable=True),
    sa.Column('saldo_cuenta_snapshot', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesos_fecha_hora'), 'accesos', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_accesos_id'), 'accesos', ['id'], unique=False)
    op.create_index(op.f('ix_accesos_miembro_id'), 'accesos', ['miembro_id'], unique=False)
    op.create_index(op.f('ix_accesos_registrado_por_id'), 'accesos', ['registrado_por_id'], unique=False)
    op.create_table('pagos',
    sa.Column('miembro_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CUOTA', 'INSCRIPCION', 'CONSUMO', 'ACTIVIDAD', 'MULTA', 'OTRO', name='tipopago'), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('recargo', sa.Float(), nullable=False),
    sa.Column('monto_final', sa.Float(), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', 'DEPOSITO', 'DEBITO', 'CREDITO', 'CHEQUE', 'ONLINE', name='metodopago'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', 'CANCELADO', name='estadopago'), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_periodo', sa.Date(), nullable=True),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('comprobante_url', sa.String(length=500), nullable=True),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['miembro_id'], ['miembros.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_index(op.f('ix_pagos_miembro_id'), 'pagos', ['miembro_id'], unique=False)
    op.create_index(op.f('ix_pagos_numero_comprobante'), 'pagos', ['numero_comprobante'], unique=True)
    op.create_table('accesos_eventos',
    sa.Column('acceso_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acceso_id'], ['accesos.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos_acceso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesos_eventos_id'), 'accesos_eventos', ['id'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('tipo', sa.Enum('ingreso', 'egreso', name='tipo_movimiento'), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('categoria_contable', sa.String(length=100), nullable=True),
    sa.Column('fecha_movimiento', sa.Date(), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=50), nullable=True),
    sa.Column('comprobante_url', sa.String(length=500), nullable=True),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_caja_id'), 'movimientos_caja', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_caja_id'), table_name='movimientos_caja')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_accesos_eventos_id'), table_name='accesos_eventos')
    op.drop_table('accesos_eventos')
    op.drop_index(op.f('ix_pagos_numero_comprobante'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_miembro_id'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_accesos_registrado_por_id'), table_name='accesos')
    op.drop_index(op.f('ix_accesos_miembro_id'), table_name='accesos')
    op.drop_index(op.f('ix_accesos_id'), table_name='accesos')
    op.drop_index(op.f('ix_accesos_fecha_hora'), table_name='accesos')
    op.drop_table('accesos')
    op.drop_index(op.f('ix_miembros_qr_code'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_numero_miembro'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_numero_documento'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_id'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_estado'), table_name='miembros')
    op.drop_index(op.f('ix_miembros_email'), table_name='miembros')
    op.drop_table('miembros')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_eventos_acceso_id'), table_name='eventos_acceso')
    op.drop_table('eventos_acceso')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###