"""add_actividades_table

Revision ID: f0fe84dc3ac9
Revises: 9d5e401eb1d6
Create Date: 2025-11-05 01:08:24.956768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fe84dc3ac9'
down_revision = '9d5e401eb1d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MIEMBRO_CREADO', 'MIEMBRO_EDITADO', 'MIEMBRO_ELIMINADO', 'MIEMBRO_SUSPENDIDO', 'MIEMBRO_REACTIVADO', 'PAGO_REGISTRADO', 'PAGO_ANULADO', 'ACCESO_PERMITIDO', 'ACCESO_DENEGADO', 'LOGIN_EXITOSO', 'LOGIN_FALLIDO', 'LOGOUT', 'CATEGORIA_CREADA', 'CATEGORIA_EDITADA', 'REPORTE_GENERADO', 'REPORTE_EXPORTADO', 'EMAIL_ENVIADO', 'RECORDATORIO_MASIVO', name='tipoactividad'), nullable=False),
    sa.Column('severidad', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='nivelseveridad'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_entidad_id'), 'actividades', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_actividades_entidad_tipo'), 'actividades', ['entidad_tipo'], unique=False)
    op.create_index(op.f('ix_actividades_fecha_hora'), 'actividades', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_actividades_id'), 'actividades', ['id'], unique=False)
    op.create_index(op.f('ix_actividades_tipo'), 'actividades', ['tipo'], unique=False)
    op.create_index(op.f('ix_actividades_usuario_id'), 'actividades', ['usuario_id'], unique=False)
    # NOTA: No eliminar índices soft_delete (idx_*) - fueron creados manualmente en migración anterior
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: No recrear índices soft_delete aquí - pertenecen a otra migración
    op.drop_index(op.f('ix_actividades_usuario_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_tipo'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_fecha_hora'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_entidad_tipo'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_entidad_id'), table_name='actividades')
    op.drop_table('actividades')
    # ### end Alembic commands ###